name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite://database.db"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Migrate database
        run: |
          cargo install --version=0.8.0 sqlx-cli --no-default-features --features sqlite
          cargo sqlx database setup
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
